#!/usr/bin/env bash
# Installs /peacock as a Codex CLI custom prompt.
# Renders the canonical pipeline (skills/peacock/SKILL.md) into
# ~/.codex/prompts/peacock.md with this checkout's absolute path baked in,
# so Codex can find the bundled scripts and rulebooks.
#
# Re-run after every `git pull` of this repo to pick up pipeline changes.
set -euo pipefail

PEACOCK_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SKILL="$PEACOCK_HOME/skills/peacock/SKILL.md"
PROMPTS_DIR="${CODEX_HOME:-$HOME/.codex}/prompts"
TARGET="$PROMPTS_DIR/peacock.md"

mkdir -p "$PROMPTS_DIR"
# Drop the YAML frontmatter (Claude Code metadata), then bake in the install path.
# The substitution uses bash string replacement, not sed, so paths containing
# sed-special characters (&, |, \) survive intact.
BODY="$(awk 'NR==1 && /^---$/ {inFrontmatter=1; next} inFrontmatter && /^---$/ {inFrontmatter=0; next} !inFrontmatter' "$SKILL")"
{
  echo "<!-- Generated by install-codex.sh from $SKILL -->"
  echo "<!-- Do not edit: change the source file and re-run the installer. -->"
  printf '%s\n' "${BODY//\$\{CLAUDE_PLUGIN_ROOT\}/$PEACOCK_HOME}"
  echo
  echo "Prompt arguments (a PR number selects PR mode; empty means full pipeline): \$ARGUMENTS"
} > "$TARGET"

echo "Installed Codex prompt: $TARGET"
echo
echo "Interactive:  codex  →  /peacock            (or /peacock <pr-number>)"
echo "Headless:     codex exec --full-auto \"\$(cat \"$TARGET\") -- run the full pipeline\""
